<?php

namespace Ito\WifiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ito\WifiBundle\Entity\Country;

/**
 * TNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{

    public function findAllCountries()
    {

        $batchSize = 10;
        $i = 0;
        $em = $this->getEntityManager();
        $q = $em->createQuery('select c from ItoWifiBundle:Country c WHERE c.active = 1');

        $iterableResult = $q->iterate();
        $data = array();

        foreach($iterableResult AS $row) {
            $country = $row[0];
            $data[] = array('id'    => $country->getId(),
                            'name'  => $country->getName());

            if (($i % $batchSize) == 0) {
                $em->clear();
            }
            ++$i;
        }

        return $data;

    }


    public function findAllCountriesAndCities()
    {
        $data = $this->findBy(array(), array('name' => 'ASC'));

        $returnCountries = array();

        foreach ($data as $country) {
            $cntry = $country->toArray();
            if($cntry['showInList'])
                $returnCountries[] = $cntry;
        }
        return $returnCountries;

    }

}
